### ISSUE TITLE
Eject fails: Cannot find module '@react-native-community/cli/build/tools/generator/copyProjectTemplateAndReplace

### ISSUE THREAD

**Issue by liftyourgame** [ramyareye/react-native-eject#1]
Trying to regenerate ios folder.

npm i react-native-eject

running:
react-native eject
gives:
warn Your project is using deprecated "rnpm" config that will stop working from next release. Please use a "react-native.config.js" file to configure the React Native CLI. Migration guide: https://github.com/react-native-community/cli/blob/master/docs/configuration.md
error Cannot find module '@react-native-community/cli/build/tools/generator/copyProjectTemplateAndReplace'. Run CLI with --verbose flag for more details.
Error: Cannot find module '@react-native-community/cli/build/tools/generator/copyProjectTemplateAndReplace'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/greg/Documents/development/sologic/upwork/causelink/node_modules/react-native-eject/build/eject.js:15:38)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by ramyareye** [comment]
Hi,
it says you're using an old version of react-native
what version is it?

**Comment by liftyourgame** [comment]
react-native: 0.61.5 => 0.61.5

**Comment by ramyareye** [comment]
I just initialized a new one and it worked well, probably you need to delete node_modules and yarn again

**Comment by liftyourgame** [comment]
Did :
rm -rf node_modules
npm i
npm i -g react-native-cli

Still get the error.

**Comment by ramyareye** [comment]
I just checked the sources again and everything seems ok!
possible to try on a new project with `npx react-native init AwesomeProject`?

**Comment by behigh** [comment]
just install `npm i @react-native-community/cli`

**Comment by JacobDel** [comment]
Did not work: https://github.com/ramyareye/react-native-eject/issues/6
